import type { Metadata } from "next";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v14-appRouter";
import { ThemeProvider } from "@royportas/design-system";

export const metadata: Metadata = {
	title: "Next App Template",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body>
				<AppRouterCacheProvider>
					<ThemeProvider theme="dark">{children}</ThemeProvider>
				</AppRouterCacheProvider>
			</body>
		</html>
	);
}
